### ISSUE TITLE
Querry on data-augmentation -using-generative-adversiral-networks

### ISSUE THREAD

**Issue by kavi0786** [sourabbapusridhar/data-augmentation-using-generative-adversarial-networks#4]
Sir,
   i have seen your repository for "data augmentation using gans". In this code, segmentation dataset is used . How we can generate the images using normal dataset for classification task. Thanks in advance.

Regards,
Kavitha

**Comment by sourabbapusridhar** [comment]
Hello Kavitha,

The dataset that we are actually using is the Cityscapes dataset ([Link](https://www.cityscapes-dataset.com/)). So, if I understood your question correctly (You are looking for actual images for your application), you can find the actual images and their corresponding segmentation maps in the dataset itself. I hope my answer was helpful.

Kind Regards,
Sourab
